### ISSUE TITLE
CSRF not implemented

### ISSUE THREAD

**Issue by Awlexus** [swelham/ueberauth_microsoft#29]
https://github.com/swelham/ueberauth_microsoft/pull/25 updated the ueberauth to version 0.7, which requires strategies to prevent CSRF attacks. 

Because the library was simply updated, and no protection added, every attempt to sign in results in an error. I would therefore recommend retiring the version `0.11.0`.

**Comment by swelham** [comment]
Thanks for reporting. I totally missed that and will retire `0.11.0`.

**Comment by swelham** [comment]
Now retired and release `0.12.0` has been published with a rollback to ueberauth 0.6 until the feature can be implemented.
