### ISSUE TITLE
Merge extra scopes with default scopes

### ISSUE THREAD

**Issue by rhblind** [swelham/ueberauth_microsoft#37]
Hi,
I previously submitted a PR which contains a flaw where the given `:extra_scopes` is not merged with default scopes. Sorry about that 😕

I have submitted a new PR #36 which fixes this issue (and also bumps a patch version).

**Comment by swelham** [comment]
Hey, no worries, I completely missed that as well!

Now merging you're PR and will get the patch published to hex.

**Comment by rhblind** [comment]
Great, thank you very much 😋

**Comment by swelham** [comment]
Np, that's now on hex and thanks for the fix 😃
