### ISSUE TITLE
Authorize and token url on dynamic tenant_id

### ISSUE THREAD

**Issue by pipegory** [swelham/ueberauth_microsoft#63]
Hi, 
when use dynamic config, the authorize and token url must be setted, because the tenant_id variable is only readed from env config

https://github.com/swelham/ueberauth_microsoft/blob/dd84b84521cafddf4095419c5c207b2a919bab05/lib/ueberauth/strategy/microsoft/oauth.ex#L45

`  defp defaults(config) do
    tenant_id = config[:tenant_id] || "common"

    [
      strategy: __MODULE__,
      site: "https://graph.microsoft.com",
      authorize_url: "https://login.microsoftonline.com/#{tenant_id}/oauth2/v2.0/authorize",
      token_url: "https://login.microsoftonline.com/#{tenant_id}/oauth2/v2.0/token",
      request_opts: [ssl_options: [versions: [:"tlsv1.2"]]]
    ]
  end`

**Comment by swelham** [comment]
Hey @pipegory, I believe this should now be fixed as part of https://github.com/swelham/ueberauth_microsoft/pull/64 that adds support for dynamic config.
